### ISSUE TITLE
Potential bugs from accidental merge of #97

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#101]
I'm a complete idiot and merged #97 instead of #98. This may have lead to bugs in dev. Please check for any before closing this issue.

Also, before merging a PR, **_CHECK IT'S THE RIGHT ONE_**

**Comment by Graphcalibur** [comment]
OK so I only found out now that you can actually zoom in and move around in the level select menu. That clears up the issue of enemy preview being cut off by the bottom.

The game still doesn't add any new towers you've made to the UI, though.

**Comment by vincetiu8** [comment]
Fixed by #102.
