### ISSUE TITLE
Level Select menu is laggy when zoomed in

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#108]
Pretty much the title. FPS drops from ~60 to ~40 and even ~20 when zoomed in enough, which makes scrolling around at a high zoom very slow.

**Comment by vincetiu8** [comment]
Hmm I wonder why... I've also noticed this. Perhaps due to the large image being moved around?

**Comment by Graphcalibur** [comment]
I think it's because of the body_image having to be transformed into a really big size when the zoom is high. One idea I had for this was to only transform the image when zooming in/out, but I tested this and while scrolling around was faster, zooming in/out became really laggy.

Loading the zoomed in body_images beforehand could work, though it would increase the loading time and it would also up the memory usage of the game. Tested this out and the memory usage bumped up from ~70,000 KB to ~800,000 KB
