### ISSUE TITLE
Extend functionality of Tower Preview

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#117]
Right now the tower preview has very specific requirements for which towers can be made. The preview could be improved to allow adding towers which have more/less than 3 stages, don't shoot projectiles (and thus not have a projectile sprite or audio), or only have a base sprite and not a gun sprite.

Also, the cost of the tower is called "upgrade cost" even if it's at stage 0.

**Comment by vincetiu8** [comment]
Hmm. Thought I fixed the cost already, may have resurfaced as part of the refactoring in #109.

I'll add these attributes, which will need updating of the attributes.json file. Please add any more attributes requested to #2, as this issue extends #2.

**Comment by Graphcalibur** [comment]
I think this has been mostly addressed already.
