### ISSUE TITLE
Differentiate Start and End tiles

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#132]
The start and end tiles look exactly the same which makes it hard for a new player to tell which is which.

**Comment by vincetiu8** [comment]
Also, maybe we can make them something more interesting than green? Maybe an 'open' wound for the start?

**Comment by Graphcalibur** [comment]
I think the best way to do this would just to be to add start/end tiles to the tileset and then add them on the tilemap.

**Comment by vincetiu8** [comment]
Yeah pretty much.
