### ISSUE TITLE
Fast-forward waves

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#137]
Proposing several changes to wave updates:
- Players should manually have to start the waves, so at the very start of the game they have time to place down towers.
- Waves should have a built-in time between waves, set in settings.py. Therefore, enemies spawning in with 0 delay are still held back until the wave delay is over.
- Players should be able to fast-forward waves i.e. when all spawners are done spawning, they should be able to skip the wait times between waves.

**Comment by Graphcalibur** [comment]
Should we also delay waves until all the enemies in the previous wave are dead?

**Comment by vincetiu8** [comment]
~~We should start the countdown to the next wave once enemies have finished spawning.~~

**Comment by vincetiu8** [comment]
Actually up to you. Whatever works best.

**Comment by Graphcalibur** [comment]
It could also be an options in the waves data, along with the wave delay.
