### ISSUE TITLE
Able to place towers despite not having the required protein

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#141]
If you select a tower then upgrade one of the towers on the map, the game will still let you place down the tower you selected even if you no longer have the protein to do so after upgrading. This will also cause your protein to go below 0.

**Comment by Graphcalibur** [comment]
My idea for a solution was to just prevent the player from upgrading towers while they have a tower selected. This would also prevent things like accidentally upgrading a tower when you meant to place one down.

Having said that, this solution would require letting players "return" towers when they select one but end up deciding not to place it down.

**Comment by vincetiu8** [comment]
Yes this seems like a good idea.
