### ISSUE TITLE
Can "trap" stray enemies to instantly kill them

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#148]
Not sure if I'd really call this an issue or a bug because of how hard it is to setup but you can kill stray enemies (aka enemies that aren't on the path) by entrapping them.

Easiest way I found to set this up is on Wave 3 of Level 3 (preferably with Coronavirus health set really high). Firstly, place towers down until you manage to get this configuration: https://i.imgur.com/cTEgFko.png. Then, in Wave 3, once a bunch of Coronaviruses get in between the two sets of towers, quickly place a tower down where the tower preview in the image is, and then place another tower 1 tile above the leftmost tower. If done right, all the enemies inside the created "tower box" will instantly die.

**Comment by vincetiu8** [comment]
If an enemy is trapped, perhaps we should promote them to a 'flying' enemy i.e. not pathfind check for towers?

**Comment by Graphcalibur** [comment]
Tbh I wouldn't mind leaving it in there. It's quite hard to setup as it is.
