### ISSUE TITLE
Towers sometimes shoot backwards

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#155]
Sometimes, the tower bullets fire backward. I can't find a way to replicate this, but going to level 3 and playing for a bit should be able to spawn some instances of this issue.

**Comment by Graphcalibur** [comment]
Hmm I haven't been able to replicate this either. Could you show a video recording of this?

**Comment by vincetiu8** [comment]
I'll record one if I can find another example.

**Comment by Graphcalibur** [comment]
Has this issue occurred recently?

**Comment by vincetiu8** [comment]
I haven't seen this recently either.
