### ISSUE TITLE
Starting a level crashes the game

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#162]
Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "data/main.py", line 62, in run
    self.draw()
  File "data/main.py", line 71, in draw
    surf = self.current_display.draw()
  File "data/menus.py", line 688, in draw
    start_btn = self.start_btn
AttributeError: 'TowerSelectMenu' object has no attribute 'start_btn'

This seems to only have been an issue after commit 4d15a8e. Also, this is a really strange error because it seems like the constructor of the TowerSelectMenu isn't running for some reason...

**Comment by Graphcalibur** [comment]
Nevermind, just noticed that there are 2 TowerSelectMenus in menus.py haha

**Comment by vincetiu8** [comment]
Wth ok
