### ISSUE TITLE
Pathfinding doesn't always pick the optimal route

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#167]
Example: https://i.imgur.com/jqEB3Rb.png

For the three goals at the bottom-center of the map, the pathfinding chooses to go to the leftmost one instead of the rightmost one.

**Comment by vincetiu8** [comment]
Huh I'll check on this.

**Comment by Graphcalibur** [comment]
It can also be seen in the Level 3 map, as it would be more optimal for the bottom starts to go to the bottom goals, yet they don't do this for some reason.
