### ISSUE TITLE
Only path of start0 is shown

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#169]
Similar to #167, this is probably an issue with current optimization of pathfinding routes. The game only shows the route from start0 to the goal, and ignores other starts. This can be seen on the final wave of level2.

**Comment by Graphcalibur** [comment]
I believe this is a general issue with the paths not being redrawn between different waves unless you place down a tower. This can also be seen at the end of Wave 2 of Level 2 where the path won't go back to normal unless you place a tower.
