### ISSUE TITLE
Removing the LIBPNG error converts the images to index color format

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#170]
Is this an issue or is there another root cause? For some reason when I run ImageMagick it converts the images to Index as well. The issue is index images don't like being filled in with pygame RGB/RGBA, so it causes the bases to become invisible, etc.

**Comment by Graphcalibur** [comment]
Yeah, I'm pretty sure this is the cause of the issue as I noticed it happening to some of the images after I ran the ImageMagick conversion on them. I was able to fix this by opening the converted image file in GIMP, deleting the alpha channel of the image, and adding it again while deleting the necessary parts to make the background transparent.

**Comment by Graphcalibur** [comment]
Nevermind, this method stopped working for some reason.

Tbh I feel like the easiest thing to do at this point would just be to suppress the libpng warning messages from appearing and leave the images as is if they look fine.

**Comment by Graphcalibur** [comment]
OK, I think I've found a better way to fix the libpng issue using GIMP that doesn't mess with the rendering (https://wiki.archlinux.org/index.php/Libpng_errors). I'll just fix any libpng-error-causing images in my PRs.
