### ISSUE TITLE
Add protein (aka money) and upgrades

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#18]
Add a system for spending protein to build and upgrade towers + earning protein from killing enemies.

**Comment by vincetiu8** [comment]
If u look at the mapping #17 it adds a singular gun to each tower. Perhaps upgrades can add further guns and/or more damage?

**Comment by vincetiu8** [comment]
This has been fixed by #25, but I think we can add a few more things:
- The player should be able to start with a certain amount of protein.
- Towers can have a bar (for now) above them showing what their level is.
- The protein amount can be shown using text on the screen (more on this in #28)

**Comment by Graphcalibur** [comment]
Closing this unless someone has an interesting idea to spice up the protein mechanic.
