### ISSUE TITLE
Tie levels to the different body parts

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#193]
Instead of having big level buttons with numbers on them, it would be better if we put markers on the relevant body parts as the "level" buttons.

By the way, I was wondering if the levels should start from the mouth and go inwards into the body, or the other way around. The former is more natural, but I feel like the latter makes more sense since the body is pushing the invasion back starting from the inside.

**Comment by vincetiu8** [comment]
I think we should do the former. It also feels more natural and we can say the more vital organs are the ones the viruses are going after more.
