### ISSUE TITLE
Add support for multiple levels per body part

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#202]
I think it would be nice if there could be multiple levels that use the same map so we can have more than just 1 level per map.

**Comment by Graphcalibur** [comment]
One idea I had for this was to have multiple "bodies", and each body had their own unique level for each body part.

**Comment by vincetiu8** [comment]
Ah that sounds like a good idea!

**Comment by vincetiu8** [comment]
Or more like an easy/medium/hard style thing with one body so they select which one. The harder game modes can give a multiplier to the amount of protein (high score)

**Comment by vincetiu8** [comment]
Oh and they need to complete the 'easy' before being able to play on 'medium' and so on.
