### ISSUE TITLE
Merge dev back into master

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#203]
We should target these issues first and, once all resolved, merge dev back into master to create a 'save':
- #174 
- #201 
- #202

**Comment by vincetiu8** [comment]
I'm adding #210, #211 and #216 here.

**Comment by Graphcalibur** [comment]
Once #234, #236, #240, #241, #244, and #245 are done, we should focus on this so we can make a more updated demo. If you want, we can even send that demo off to a couple of people to get some feedback.
