### ISSUE TITLE
Add 'new enemy appeared' screen

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#210]
Whenever a player sees a new enemy that they haven't seen before, they should be informed of the enemy's stats and background/description by a pop-up in game.

**Comment by vincetiu8** [comment]
And before they have seen an enemy a question mark should appear over its greyed out sprite in the tower select and it shouldn't show up in the enemy preview.

**Comment by Graphcalibur** [comment]
Leaving this issue up until this gets implemented

> And before they have seen an enemy a question mark should appear over its greyed out sprite in the tower select and it shouldn't show up in the enemy preview.

**Comment by vincetiu8** [comment]
Ah yes, forgot about this and will implement it.
