### ISSUE TITLE
Game Screen Doesn't show anything on a Mac

### ISSUE THREAD

**Issue by haridenton** [Invincibot/covid-tower-defense#23]
I have downloaded the entire repo and tried running it on my Mac OsCatalina version 10.15.3 (19D76).

When I run main.py, I get no errors apart from the "libpng warning: iCCP: known incorrect sRGB profile" issue but it doesn't show anything, no tile_map, no sprites.

<img width="1186" alt="Screenshot 2020-04-09 at 3 46 18 PM" src="https://user-images.githubusercontent.com/2960983/78871017-a2d94180-7a79-11ea-9907-2757f2ba3d6a.png">

**Comment by vincetiu8** [comment]
It looks like pygame 1.9.6 doesn't like OS Catalina. Try installing pygame 2.0.0.dev6. I think that should solve the problem.

**Comment by haridenton** [comment]
Thanks. That literally solved the problem. 

Weird though as pygamezero uses the older version of pygame and works fine on my Mac.
