### ISSUE TITLE
Aoe buff towers don't buff other aoe buff towers

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#237]
Is this supposed to happen?

**Comment by Graphcalibur** [comment]
Yeah. This was mainly done to prevent the monocyte from buffing the range of other AOE buff towers since they're balanced around only being able to buff a certain number of towers at each stage.

Also you'd probably get a weird infinite loop if you put 2 monocytes next to each other.

**Comment by vincetiu8** [comment]
Hahaha ok
