### ISSUE TITLE
Game hangs when it is closed

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#24]
Basically the title. Closing the game sometimes results in it hanging, requiring the user to go to task manager to kill it. I have no idea what causes this, though the I've seen this issue appear in all commits from af40b7d onwards (haven't tried out the ones before it). Will experiment more with this later.

**Comment by vincetiu8** [comment]
@Graphcalibur is this fixed by #31?

**Comment by Graphcalibur** [comment]
No. Seems like it might just be an issue on my end, though.

**Comment by vincetiu8** [comment]
Is this fixed now @Graphcalibur?

**Comment by Graphcalibur** [comment]
Nope. I actually have no idea what is causing this since it's been a problem for me since the beginning.
