### ISSUE TITLE
Make level infos reflect the existence of multiple difficulties for each body part

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#246]
The level infos are outdated now that there are multiple difficulties per body part. It's awkward for the infos to only show the data for the Mild difficulty but it's also awkward for the infos to show the combined data for all difficulties. There are two ways I can think of to fix this: either changing the difficulty system or the data on the level infos.

For the first way, the change to the difficulty system would be the difficulty being set on the level select menu rather than the tower select menu. This way, we can have the level info show the enemies, difficulty, and number of waves for each body part's difficulty. The second way would involve simply removing the enemies/number of waves/difficulty from the level infos.

I prefer the first way since it retains much of the information on the level info , but I want your input on this as well @Invincibot

**Comment by vincetiu8** [comment]
I would suggest a third way: add all the enemies from all difficulties to the level preview menu. So users see all enemies in all difficulties? Idk the first method seems good as well.

**Comment by Graphcalibur** [comment]
It feels a bit messy to put the enemies from all difficulties on the level info, especially since some of the enemies won't show up depending on the difficulty chosen. I'll implement the first method then.

**Comment by Graphcalibur** [comment]
I'll keep this here until descriptions/difficulties become specific to each difficulty as well.
