### ISSUE TITLE
Add a UI to the game

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#28]
It would be nice if players could look somewhere on the screen (top right?) that has all the information such as:
- Lives
- Protein

**Comment by Graphcalibur** [comment]
I think at the default zoom level, the UI shouldn't cover up any part of the map so that the player can opt to always keep it open while still being able to see the whole map.

**Comment by vincetiu8** [comment]
Thing is though that gets tricky. If you look at the camera function it auto resizes the map so the minimum zoom is where the map barely fits into the screen. If we get to later in the game where we have maps of other sizes, it may not work...

**Comment by vincetiu8** [comment]
Linking to #2, users should be able to see the towers and select from them in the UI. No scrolling UI needed, their selection of towers should be limited per level.

**Comment by Graphcalibur** [comment]
One thing we can add to the ui is to make the towers which have a higher cost than the player's current protein greyed out to make it clearer that they can't be placed.
