### ISSUE TITLE
Add enemy waves

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#29]
Right now enemies kinda all come at random spawning times. This is ok, but there should also be an option to 'load' waves of enemies, possibly from an xml file or some other form of data storage.

**Comment by Graphcalibur** [comment]
I think JSON would be a pretty good way to store the enemy waves data

**Comment by vincetiu8** [comment]
Sounds good! I'd have a look at YAML too just in case.

**Comment by vincetiu8** [comment]
Also, try to integrate another enemy / options to add one to this branch so we can address all the enemy issues in one go!

**Comment by Graphcalibur** [comment]
Partially addressed by PR #40 but the following functionality are still missing:

- Loading enemy types. I haven't added any new enemies yet, so the program just loads the default enemy and ignores the "enemy_type" attribute. This also ties into issue #1.
- Win screen. Right now the program just doesn't spawn any more enemies when all the waves are finished.

It might also be a good idea to make an easy-to-use wave generator program so more people can contribute by making waves.
