### ISSUE TITLE
Add "arteries" and "veins"

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#47]
Sorta like adding bridges but more body themed. This would mean enemies can go up and down the bridge or a series of bridges or tunnels. This creates the oppurtunity for more routes but may (will) cause serious pathfinding changes.

**Comment by Graphcalibur** [comment]
Hm I'm not sure I understand what you mean by arteries and veins. Is it just the sames as normal paths but with different looking tilesets?

**Comment by vincetiu8** [comment]
I'll be the one to implement this, so you can see what I mean...

**Comment by vincetiu8** [comment]
Fixed by #58.
