### ISSUE TITLE
Improve Game Over/Win screen

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#50]
Right now the Game Over and Win screen are both pretty anticlimactic and could be made a lot more interesting, even if the text is just made more stylish (like WordArt).

You should also be able to go back to the level select screen instead of only being able to restart the current level. Maybe a window pop ups that has two buttons: one which restarts the level and one that goes back to the level screen.

**Comment by vincetiu8** [comment]
Partially fixed by #57 but we should work towards having someone from art design game over and win screens.

**Comment by Graphcalibur** [comment]
Mostly addressed by #59 but it can still be made a bit more interesting.

Some ideas I had:
- Audio for the "You Died" screen would be a heartrate monitor flatlining while the one for the "You Survived" screen would be a normal heartbeat.
- Building on the above, there can also be a heartrate monitor in the background of the game over screen.
- I think it would be pretty funny if winning the last level brought up the "You Died" screen but the cause of death would simply be "Old Age"

**Comment by vincetiu8** [comment]
Hahahaha sounds good!
