### ISSUE TITLE
Make a 'callable' tilesize variable

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#55]
It is annoying when whenever we want to access the tilesize we have to go through self.game.map.tilesize, and the helper functions for tilemap need a tilesize. This ties in with #27 with cleaning up the settings file in general.

**Comment by vincetiu8** [comment]
I've decided this is wayyy too hard.

**Comment by vincetiu8** [comment]
Actually @Graphcalibur u may want to look at this. I can't figure out a way but it may optimize the game a little.

**Comment by Graphcalibur** [comment]
Hm I'm not really sure what you mean by a "callable" tilesize variable. Do you mean like putting the tilesize of the map outside of tilemaps.py and into settings.py?

**Comment by vincetiu8** [comment]
Yea more or less.

**Comment by vincetiu8** [comment]
I've labeled this as wontfix for now as I don't think this will be fixed for the foreseeable future.
