### ISSUE TITLE
FPS counter doesn't work

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#60]
Just like the title says. When we start the level the FPS is stuck at 0.00. The game still plays, just interested on why it displays 0 now.

**Comment by Graphcalibur** [comment]
self.clock.tick() has to be called every frame so that the clock updates and displays the FPS properly

**Comment by vincetiu8** [comment]
Are we calling it?

**Comment by Graphcalibur** [comment]
Nope.
