### ISSUE TITLE
Add an 'upgrades' menu

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#71]
Players should earn some DNA/protein from completing a level (NOT finishing one, completing one, so they can only gain the DNA/protein once. They should then be able to spend this on unlocking towers and increasing the starting protein and stuff.

**Comment by Graphcalibur** [comment]
I think it would be a pretty cool idea if the game would keep track of the player's "High Score" for each level, with the score being the amount of leftover protein at the end of the level. The amount of currency the player has for spending in the upgrades menu (assuming they don't spend anything) would be the sum of all of their High Scores. This system would encourage players to play levels more optimally and make more efficient use of their towers.

**Comment by vincetiu8** [comment]
Ah fax.

**Comment by vincetiu8** [comment]
We're gonna have to do a lot of level balancing then though.
