### ISSUE TITLE
Optimize game

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#73]
The game lags hard when more than 500 enemies are on the screen. This seems pretty obvious but we should look into any optimization we can do to reduce this.

**Comment by Graphcalibur** [comment]
I've also noticed the game lags hard while the game over or pause screen is fading in. I'll see if there's a way to optimize this.

**Comment by vincetiu8** [comment]
Is there anything else you can think of @Graphcalibur? Otherwise, we should close this issue.

**Comment by Graphcalibur** [comment]
Can't think of any right now. At least, none that are really noticeable.
