### ISSUE TITLE
Game crashes when removing a tower

### ISSUE THREAD

**Issue by Graphcalibur** [Invincibot/covid-tower-defense#88]
Missed this bug when testing the multi-start PR. Removing a tower in level 2 or 3 causes the game to crash with the following error message:

Traceback (most recent call last):
  File "main.py", line 573, in <module>
    g.run_game()
  File "main.py", line 33, in run_game
    self.events()
  File "main.py", line 88, in events
    self.game.event(event)
  File "main.py", line 552, in event
    self.path = self.pathfinder.astar(tile_map, ((tile_from_xcoords(self.starts[0].x, self.map.tilesize),
AttributeError: 'Start' object has no attribute 'x'

**Comment by vincetiu8** [comment]
Oh I see. Will fix.
