### ISSUE TITLE
Make a parent class for displays

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#89]
For issues #82, #83 and #84, as well as future updates to menus of the game, it would be nice to have a parent class which would simplify function calls as the game could just call the parent and then the children would overwrite them.

**Comment by vincetiu8** [comment]
@Graphcalibur maybe you should handle this as I'm not experienced on the draw method for the Game due to changes from the gameover and pause screens.

**Comment by vincetiu8** [comment]
So what I was thinking is when the game needs to change screens the running class (Menu, Game, Game_Over) can change the game's current_display variable to the next display and so it will be easier to manage screens without boolean hell in the main class.

**Comment by Graphcalibur** [comment]
I think I get what you mean but what does this have to do with #82, #83, and #84?

**Comment by vincetiu8** [comment]
Actually I made a mistake. This has nothing to do with #82, #83 and #84.

**Comment by vincetiu8** [comment]
Also is it possible to integrate the tower preview and enemy preview menu with this? I used some slightly weird mechanics for those menus and we need to add a camera to them but I think it could work...

**Comment by Graphcalibur** [comment]
By integrate, do you mean making them displays so the Main class can switch to them instead of just having them being drawn on top of the level select menu?

**Comment by vincetiu8** [comment]
Yeah pretty much.
