### ISSUE TITLE
Bullets sometimes still miss

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#92]
Sometimes the bullets we shoot out still miss the enemies.

**Comment by Graphcalibur** [comment]
For the towers that automatically track enemies, we can make them fire hitscan projectiles that instantly hit the enemy they're tracking. Preferably with a graphical firing effect so the player can see them firing.

**Comment by vincetiu8** [comment]
Ah so like a ray instead. I see.

**Comment by vincetiu8** [comment]
Is this still an issue?

**Comment by Graphcalibur** [comment]
Think so.
