### ISSUE TITLE
Enemies lag when screen is moved around

### ISSUE THREAD

**Issue by vincetiu8** [Invincibot/covid-tower-defense#93]
Can we make it so the game auto pauses when the screen is moved?

**Comment by Graphcalibur** [comment]
I don't seem to have this issue -- game still updates as normal even when the screen is moving.

**Comment by vincetiu8** [comment]
I still think it would be nice to auto-pause the game when the user is moving the screen around.

**Comment by Graphcalibur** [comment]
This is trickier than I expected. The easiest solution would just be to force the game to run in fullscreen to be honest.
